[package]
name = "rust-rsa"
version = "0.1.0"
authors = ["Sebas Arriola <sebdeveloper6952@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primal = "0.3.0"
rand = "0.8.3"
num-bigint = "0.4.0"